<a href="https://colab.research.google.com/github/govindrvinod777/My-first-Repository-A7/blob/main/Classification_Algorithm_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("wn.csv")
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
df.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
dt = df.corr()
dt

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.256131     0.671703   
volatile acidity          -0.256131          1.000000    -0.552496   
citric acid                0.671703         -0.552496     1.000000   
residual sugar             0.114777          0.001918     0.143577   
chlorides                  0.093705          0.061298     0.203823   
free sulfur dioxide       -0.153794         -0.010504    -0.060978   
total sulfur dioxide      -0.113181          0.076470     0.035533   
density                    0.668047          0.022026     0.364947   
pH                        -0.682978          0.234937    -0.541904   
sulphates                  0.183006         -0.260987     0.312770   
alcohol                   -0.061668         -0.202288     0.109903   
quality                    0.124052         -0.390558     0.226373   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.114777   0.093705            -0.153794   
volatile acidity            0.001918   0.061298            -0.010504   
citric acid                 0.143577   0.203823            -0.060978   
residual sugar              1.000000   0.055610             0.187049   
chlorides                   0.055610   1.000000             0.005562   
free sulfur dioxide         0.187049   0.005562             1.000000   
total sulfur dioxide        0.203028   0.047400             0.667666   
density                     0.355283   0.200632            -0.021946   
pH                         -0.085652  -0.265026             0.070377   
sulphates                   0.005527   0.371260             0.051658   
alcohol                     0.042075  -0.221141            -0.069408   
quality                     0.013732  -0.128907            -0.050656   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.113181  0.668047 -0.682978   0.183006   
volatile acidity                  0.076470  0.022026  0.234937  -0.260987   
citric acid                       0.035533  0.364947 -0.541904   0.312770   
residual sugar                    0.203028  0.355283 -0.085652   0.005527   
chlorides                         0.047400  0.200632 -0.265026   0.371260   
free sulfur dioxide               0.667666 -0.021946  0.070377   0.051658   
total sulfur dioxide              1.000000  0.071269 -0.066495   0.042947   
density                           0.071269  1.000000 -0.341699   0.148506   
pH                               -0.066495 -0.341699  1.000000  -0.196648   
sulphates                         0.042947  0.148506 -0.196648   1.000000   
alcohol                          -0.205654 -0.496180  0.205633   0.093595   
quality                          -0.185100 -0.174919 -0.057731   0.251397   

                       alcohol   quality  
fixed acidity        -0.061668  0.124052  
volatile acidity     -0.202288 -0.390558  
citric acid           0.109903  0.226373  
residual sugar        0.042075  0.013732  
chlorides            -0.221141 -0.128907  
free sulfur dioxide  -0.069408 -0.050656  
total sulfur dioxide -0.205654 -0.185100  
density              -0.496180 -0.174919  
pH                    0.205633 -0.057731  
sulphates             0.093595  0.251397  
alcohol               1.000000  0.476166  
quality               0.476166  1.000000

In [ ]:
df.duplicated().sum()
df.drop_duplicates()
df.duplicated().sum()

np.int64(240)

In [ ]:
print("Columns : ")
df.shape[1]

Columns : 


12

In [ ]:
print("Rows : ", df.shape[0])

Rows :  1599


In [ ]:
df = df.drop_duplicates(keep=False)
print("Ok : ", df.shape)

Ok :  (1139, 12)


In [ ]:
dt = pd.get_dummies(df, dtype="int64")
dt.corr().head()

fixed acidity  volatile acidity  citric acid  \
fixed acidity          1.000000         -0.255646     0.661276   
volatile acidity      -0.255646          1.000000    -0.551735   
citric acid            0.661276         -0.551735     1.000000   
residual sugar         0.109990         -0.008420     0.147385   
chlorides              0.078047          0.047435     0.217638   

                  residual sugar  chlorides  free sulfur dioxide  \
fixed acidity           0.109990   0.078047            -0.120918   
volatile acidity       -0.008420   0.047435            -0.035168   
citric acid             0.147385   0.217638            -0.026417   
residual sugar          1.000000  -0.011715             0.115296   
chlorides              -0.011715   1.000000            -0.006072   

                  total sulfur dioxide   density        pH  sulphates  \
fixed acidity                -0.087440  0.674735 -0.689535   0.204315   
volatile acidity              0.066319  0.026450  0.260102  -0.257381   
citric acid                   0.065436  0.349051 -0.557196   0.350256   
residual sugar                0.199609  0.277709 -0.083095  -0.035341   
chlorides                     0.044126  0.187093 -0.279146   0.423228   

                   alcohol   quality  
fixed acidity    -0.059456  0.110252  
volatile acidity -0.193918 -0.404703  
citric acid       0.101647  0.232096  
residual sugar    0.096543  0.011320  
chlorides        -0.226222 -0.132698

In [ ]:
x=dt.drop(['quality'], axis=1)
y=dt['quality']
print(y)

1       5
2       5
3       6
5       5
6       5
       ..
1593    6
1594    5
1595    6
1597    5
1598    6
Name: quality, Length: 1139, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=42, test_size=0.25)
x_train.shape

(854, 11)

In [ ]:
from sklearn.linear_model import LogisticRegression
legit_model = LogisticRegression()
legit_model.fit(x_train, y_train)
y_pred = legit_model.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print("Precision Score : ", precision_score(y_test, y_pred, average="macro"))
print("Recall Score : ", recall_score(y_test, y_pred, average='macro'))
print("F1 Score : ", f1_score(y_test, y_pred, average='macro'))

Accuracy :  0.48771929824561405
Confusion Matrix : 
 [[ 0  0  4  0  0  0]
 [ 0  0  9  6  0  0]
 [ 0  1 81 28  0  0]
 [ 0  0 51 58  0  0]
 [ 0  0  5 37  0  0]
 [ 0  0  0  5  0  0]]
Precision Score :  0.16213930348258707
Recall Score :  0.21141228801779258
F1 Score :  0.18340719637015934


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
