<a href="https://colab.research.google.com/github/govindrvinod777/My-first-Repository-A7/blob/main/Govind1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr1 = np.arange(10, 50)

arr1_reshaped = arr1.reshape(4, 10)

last_column = arr1_reshaped[:, -1]

print("Last Column:")
print(last_column)

Last Column:
[19 29 39 49]


In [2]:
matrix1 = np.full((3, 3), 5)

matrix2 = np.arange(1, 10).reshape(3, 3)

matrix_sum = matrix1 + matrix2

matrix_product = matrix1 * matrix2

matrix_transpose = matrix_product.T

print("Matrix Sum:")
print(matrix_sum)
print("\nMatrix Product (Element-wise):")
print(matrix_product)
print("\nTranspose of the Product:")
print(matrix_transpose)

Matrix Sum:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matrix Product (Element-wise):
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of the Product:
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [3]:
arr3 = np.random.randint(10, 101, size=15)

replaced_values = np.sum(arr3 > 50)
arr3[arr3 > 50] = -1

print("Array after replacement:")
print(arr3)
print(f"\nNumber of values replaced: {replaced_values}")

Array after replacement:
[43 25 -1 -1 -1 30 -1 -1 -1 25 -1 14 -1 45 -1]

Number of values replaced: 9


In [4]:
arr4 = np.random.rand(5, 4)

row_max_sum = np.argmax(arr4.sum(axis=1))

arr4_normalized = arr4 / arr4.sum(axis=1)[:, None]

print("Array with Normalized Rows:")
print(arr4_normalized)
print(f"\nRow with maximum sum of values: {row_max_sum}")

Array with Normalized Rows:
[[0.39109263 0.08310542 0.48223819 0.04356376]
 [0.28436038 0.25376977 0.20523663 0.25663322]
 [0.22752076 0.35966444 0.35401181 0.05880299]
 [0.10464193 0.26677852 0.54692279 0.08165676]
 [0.34326043 0.13816561 0.28603834 0.23253562]]

Row with maximum sum of values: 1


In [5]:
import numpy as np

arr5 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

unique_elements = np.unique(arr5)

values, counts = np.unique(arr5, return_counts=True)
duplicates = values[counts > 1]

print("Unique Elements:")
print(unique_elements)

print("\nDuplicates:")

Unique Elements:
[1 3 5 7 9]

Duplicates:


In [6]:
arr6 = np.arange(1, 37).reshape(6, 6)

submatrix = arr6[1:5, 1:5]

even_numbers = submatrix[submatrix % 2 == 0]

print("Submatrix:")
print(submatrix)
print("\nEven numbers from submatrix:")
print(even_numbers)


Submatrix:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers from submatrix:
[ 8 10 14 16 20 22 26 28]


In [7]:
arr7 = np.arange(12).reshape(3, 4)

arr7_reshaped = arr7.reshape(2, 6)

arr7_flat = arr7.flatten()

arr7_final = arr7_flat.reshape(4, 3)

print("Final reshaped array (4, 3):")
print(arr7_final)


Final reshaped array (4, 3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
a = np.array([[1, 2], [3, 4]])

a_new_row = np.append(a, [[5, 6]], axis=0)

a_final = np.append(a_new_row, [[7], [8], [9]], axis=1)

print("Final array with new row and column:")
print(a_final)


Final array with new row and column:
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined_array = np.concatenate((a, b, c))

reshaped_matrix = joined_array.reshape(3, 3)

diagonal_elements = np.diag(reshaped_matrix)

print("Joined array:")
print(joined_array)
print("\nReshaped matrix:")
print(reshaped_matrix)
print("\nDiagonal elements:")
print(diagonal_elements)


Joined array:
[1 2 3 4 5 6 7 8 9]

Reshaped matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements:
[1 5 9]


In [10]:
arr10 = np.arange(1, 21)

divisible_by_3_or_5 = arr10[(arr10 % 3 == 0) | (arr10 % 5 == 0)]

count = len(divisible_by_3_or_5)

print("Values divisible by 3 or 5:")
print(divisible_by_3_or_5)
print(f"\nCount: {count}")

Values divisible by 3 or 5:
[ 3  5  6  9 10 12 15 18 20]

Count: 9
